import { Inject, Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { mockAlbums } from '../../mocks/mockAlbums';
import { API_URL } from '../../tokens';
import { HttpClient, HttpErrorResponse } from '@angular/common/http'
import { catchError, EMPTY, from, map, NEVER, Observable, of, Subscription, throwError } from 'rxjs';
import { AuthService } from '../auth/auth.service';
import { Album, AlbumSearchResponse, PagingObject } from '../../model/Search';
import { Message } from '@angular/compiler/src/i18n/i18n_ast';

@Injectable({
  providedIn: 'root'
})
export class MusicApiService {

  constructor(
    @Inject(API_URL) private api_url: string,
    private http: HttpClient,
    private auth: AuthService
  ) { }

  fetchAlbumSearchResults(query = '') {

    return this.http.get<AlbumSearchResponse>(//
      this.api_url + 'search', {
      params: {
        type: 'album', query
      },
      headers: {
        Authorization: 'Bearer ' + this.auth.getToken()
      }
    }).pipe(
      map(res => res.albums.items),
      catchError((error: unknown) => {


        if (error instanceof HttpErrorResponse) {
          if (isSpotifyErrorResponse(error.error)) {
            const res = error.error
            return throwError(() =>
              new Error(res.error.message))
          }
        }

        return throwError(() => new Error('Unexpected Error'))
      })
    )
  }
}


// Function Type Guards
function isSpotifyErrorResponse(res: any): res is SpotifyErrorResponse {
  return ('error' in res
    && 'status' in res.error
    && 'message' in res.error)
}

// Generated by https://quicktype.io
export interface SpotifyErrorResponse {
  error: {
    status: number;
    message: string;
  }
}